name: toolenv
channels:
  - pytorch
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - basemap=1.2.0
  - blas=1.0
  - bleach=3.1.4
  - boto3=1.12.36
  - botocore=1.15.36
  - bzip2=1.0.8
  - ca-certificates=2020.4.5.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cryptography=2.8
  - cycler=0.10.0
  - cython=0.29.16
  - dbus=1.13.12
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - folium=0.12.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - geos=3.6.2
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.9
  - imageio=2.8.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=2.0.14
  - jedi=0.16.0
  - jinja2=2.11.1
  - jmespath=0.9.5
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.5.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - ninja=1.10.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1f
  - pandas=1.0.3
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - plotly=4.6.0
  - proj=6.2.1
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycocotools=2.0.0
  - pycountry=19.8.18
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=2.4.1
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.9.7
  - readline=7.0
  - retrying=1.3.3
  - s3transfer=0.3.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - shapely=1.6.4
  - sip=4.19.13
  - six=1.14.0
  - spacy-model-en_core_web_lg=2.3.1
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - countryinfo==0.1.0
    - fasttext==0.9.1
    - fpdf==1.7.2
    - geonamescache==1.1.0
    - pybind11==2.5.0
    - spacy==2.3.5

